### ISSUE TITLE
Majesty of Vue.js Book

### ISSUE THREAD

**Issue by pongoman** [cody1991/awesome-vue#1]
Greetings Cody , I am opening this issue to let you know about the use of the book. I am sorry to say that we have not made any agreement about uploading or translating the book on any opensource platforms, therefore I am asking you to take it down from Github and any other pages. So far the book should be only avaiable on [Leanpub](https://leanpub.com/vuejs/) If you are interested in translating the book you can contact me at: kostas@tmvuejs.com or alex@tmvuejs.com and then talk about the details. Thank you in advance.

**Comment by pongoman** [comment]
Greetings @cody1991 , I am commenting again since you might have missed this issue. Please remove the file Majesty of Vue.js pdf and any others as well as the translated version from public access and repositories. We have not made any agreement about  the book so only the authors have the rights for these actions currently.  Please remove them and if you are interested we can talk about a translation privately.  Resolve this issue as soon as possible. Thank you

**Comment by cody1991** [comment]
OK.I am very sorry.I just download this book from [csdn](http://download.csdn.net/detail/likaiwalkman/9502306),and want to make a translated version for my trainee because your book is a nice vue guidance book.

I have delete them.So sorry~.

**Comment by pongoman** [comment]
Thank you for taking it down and for your kind words about the book. You can do a translated version but keep it secret and please do not share it with the world. If you would like to translate we could make a deal to sell the translated version of the book and share the profits, if you are into that mail me. Thanks
